# kubernetes/microservice2/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice2
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
        - name: microservice2
          image: microservice2:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: kafka:9092
            - name: KAFKA_TOPICS
              value: topic2,topic3
